using ClosedXML.Excel;
using EmployeeManagement.Api.Data;
using EmployeeManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EmployeeManagement.Api.Services;

public class ReportService(AppDbContext db)
{
    public async Task<byte[]> EmployeeDirectoryExcelAsync()
    {
        var employees = await db.Employees.Include(e => e.Department).OrderBy(e => e.EmployeeCode).ToListAsync();
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Employees");
        var headers = new[] { "Code", "Name", "Email", "Position", "Department", "Salary", "Joining Date", "Status" };
        for (var i = 0; i < headers.Length; i++) sheet.Cell(1, i + 1).Value = headers[i];
        for (var i = 0; i < employees.Count; i++)
        {
            var e = employees[i]; var r = i + 2;
            sheet.Cell(r, 1).Value = e.EmployeeCode;
            sheet.Cell(r, 2).Value = $"{e.FirstName} {e.LastName}";
            sheet.Cell(r, 3).Value = e.Email;
            sheet.Cell(r, 4).Value = e.Position;
            sheet.Cell(r, 5).Value = e.Department?.Name;
            sheet.Cell(r, 6).Value = e.Salary;
            sheet.Cell(r, 7).Value = e.JoiningDate;
            sheet.Cell(r, 8).Value = e.IsActive ? "Active" : "Inactive";
        }
        sheet.Columns().AdjustToContents();
        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public async Task<byte[]> AttendanceExcelAsync(DateTime from, DateTime to)
    {
        var rows = await db.Attendances.Include(a => a.Employee)
            .Where(a => a.AttendanceDate.Date >= from.Date && a.AttendanceDate.Date <= to.Date)
            .OrderBy(a => a.AttendanceDate).ToListAsync();
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Attendance");
        var headers = new[] { "Date", "Employee", "Code", "Status", "Check In", "Check Out", "Remarks" };
        for (var i = 0; i < headers.Length; i++) sheet.Cell(1, i + 1).Value = headers[i];
        for (var i = 0; i < rows.Count; i++)
        {
            var a = rows[i]; var r = i + 2;
            sheet.Cell(r, 1).Value = a.AttendanceDate;
            sheet.Cell(r, 2).Value = $"{a.Employee?.FirstName} {a.Employee?.LastName}";
            sheet.Cell(r, 3).Value = a.Employee?.EmployeeCode;
            sheet.Cell(r, 4).Value = a.Status;
            sheet.Cell(r, 5).Value = a.CheckIn?.ToString();
            sheet.Cell(r, 6).Value = a.CheckOut?.ToString();
            sheet.Cell(r, 7).Value = a.Remarks;
        }
        sheet.Columns().AdjustToContents();
        using var stream = new MemoryStream(); workbook.SaveAs(stream); return stream.ToArray();
    }

    public async Task<byte[]> EmployeeDirectoryPdfAsync()
    {
        var employees = await db.Employees.Include(e => e.Department).OrderBy(e => e.EmployeeCode).ToListAsync();
        QuestPDF.Settings.License = LicenseType.Community;
        return Document.Create(container => container.Page(page =>
        {
            page.Margin(30); page.Header().Text("Employee Directory").FontSize(20).Bold();
            page.Content().Table(table =>
            {
                table.ColumnsDefinition(c => { for (var i = 0; i < 6; i++) c.RelativeColumn(); });
                foreach (var h in new[] { "Code", "Name", "Position", "Department", "Salary", "Joining" }) table.Cell().Element(CellStyle).Text(h).Bold();
                foreach (var e in employees)
                {
                    table.Cell().Element(CellStyle).Text(e.EmployeeCode);
                    table.Cell().Element(CellStyle).Text($"{e.FirstName} {e.LastName}");
                    table.Cell().Element(CellStyle).Text(e.Position);
                    table.Cell().Element(CellStyle).Text(e.Department?.Name ?? "-");
                    table.Cell().Element(CellStyle).Text(e.Salary.ToString("N2"));
                    table.Cell().Element(CellStyle).Text(e.JoiningDate.ToString("yyyy-MM-dd"));
                }
                static IContainer CellStyle(IContainer c) => c.Border(1).Padding(4);
            });
            page.Footer().AlignCenter().Text(x => x.Span("Generated by Employee Management System"));
        })).GeneratePdf();
    }

    public async Task<object> DashboardAsync()
    {
        var total = await db.Employees.CountAsync();
        var active = await db.Employees.CountAsync(e => e.IsActive);
        var departments = await db.Departments.CountAsync();
        var avgSalary = await db.Employees.Select(e => (decimal?)e.Salary).AverageAsync() ?? 0;
        var hiring = await db.Employees.GroupBy(e => e.JoiningDate.Year).Select(g => new { year = g.Key, count = g.Count() }).OrderBy(x => x.year).ToListAsync();
        var deptGrowth = await db.Employees.Include(e => e.Department).GroupBy(e => e.Department!.Name).Select(g => new { department = g.Key, count = g.Count() }).OrderByDescending(x => x.count).ToListAsync();
        return new { totalEmployees = total, activeEmployees = active, departments, averageSalary = avgSalary, hiringTrend = hiring, departmentGrowth = deptGrowth };
    }
}
